services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ../src:/var/www/html
    depends_on:
      db:
        condition: service_healthy


  db:
    image: mysql:8
    container_name: parking-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: parking_db
    ports:
      - "3307:3306"
    volumes:
    - db_data:/var/lib/mysql
    - ../parking.sql:/docker-entrypoint-initdb.d/01-parking.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db_data: